stack:
  # array. extra config files should be inited together, files that in the same dir with stack.yml.
  includes:
  # registry center options
  registry:
    # string. registry middleware name. eg: mdns, etcd, consul...
    name: mdns
    # string. registry center address
    address:
    # int in seconds. register interval.
    interval: 10
    # int in seconds. register time to live.
    ttl: 15
  # broker component options
  broker:
    #
    name: http
    address:
  client:
    protocol: http
    pool:
      size:
      ttl:
  server:
    id:
    name:
    address:
    advertise:
    protocol:
    version:
    # metadata register to registry. array
    metadata:
  transport:
  selector:

  logger:
    name:
  runtime:
  profile:




